//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StAbraam.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StAbraamEntities : DbContext
    {
        public StAbraamEntities()
            : base("name=StAbraamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Clinic> Clinics { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Doctor_Cities> Doctor_Cities { get; set; }
        public virtual DbSet<Doctor_Clinic> Doctor_Clinic { get; set; }
        public virtual DbSet<Doctor_Countries> Doctor_Countries { get; set; }
        public virtual DbSet<Doctor_CurrentService> Doctor_CurrentService { get; set; }
        public virtual DbSet<Doctor_Languages> Doctor_Languages { get; set; }
        public virtual DbSet<Doctor_PreferedPeriod> Doctor_PreferedPeriod { get; set; }
        public virtual DbSet<Doctor_Specialty> Doctor_Specialty { get; set; }
        public virtual DbSet<Doctor_Sub_Specialty> Doctor_Sub_Specialty { get; set; }
        public virtual DbSet<Doctor_Suggestion> Doctor_Suggestion { get; set; }
        public virtual DbSet<Doctor_ToJoinServices> Doctor_ToJoinServices { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Mobile> Mobiles { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Sub_Specialty> Sub_Specialty { get; set; }
        public virtual DbSet<Suggestion> Suggestions { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
